"""add shopping_list to menus

Revision ID: 8e1ad5807d15
Revises: d5f0ee3eb3ce
Create Date: 2026-08-27 12:43:02.378650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '8e1ad5807d15'
down_revision: Union[str, Sequence[str], None] = 'd5f0ee3eb3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('shopping_list', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'shopping_list')
    # ### end Alembic commands ###
